source: docs
destination: _site
theme: minima
show_downloads: false
title: Motiv
description: Supercharge your boolean logic!
verbose: true
baseurl: "/Motiv"
minima:
  skin: auto
header_pages:
  - index.md
  - API.md