destination: _site
remote_theme: jekyll/minima
show_downloads: false
title: Motiv
description: Supercharge your boolean logic!
verbose: true
baseurl: "/Motiv"
minima:
  skin: auto
header_pages:
  - docs/API.md
exclude:
  - Gemfile
  - Gemfile.lock
  - _config.yml
  - .gitignore