source: docs
destination: _site
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme 
show_downloads: false
title: Motiv
description: Supercharge your boolean logic!
verbose: true
baseurl: "/Motiv"
header_pages:
  - index.md
  - Construction.md
  - Operators.md