source: docs
destination: _site
theme: minima
show_downloads: false
title: Motiv
description: Supercharge your boolean logic!
verbose: true
url: "https://karlssberg.github.io/"
baseurl: "/Motiv"
header_pages:
  - index.md
  - Construction.md
  - Operators.md