### YamlMime:ManagedReference
apiRules:
  - exclude:
      uidRegex: ^Motiv\.\w+Proposition\.PropositionBuilder
  - exclude:
      uidRegex: ^Motiv\.As\w+Extensions
  - exclude:
      uidRegex: ^Motiv\.Spec$
  - exclude:
      uidRegex: ^Motiv\.ISpecDescription$