using Microsoft.CodeAnalysis;

namespace Motiv.Explain;

/// <summary>
///     The <c>[Explain]</c> attribute the generator adds to every compilation, explain build or not, so that
///     code carrying it compiles everywhere.
/// </summary>
internal static class ExplainAttribute
{
    public const string MetadataName = "Motiv.Explain.ExplainAttribute";

    // [Conditional] drops each usage from metadata unless MOTIV_EXPLAIN is defined, so a prod assembly
    // carries no trace of which methods were marked. Explain builds keep it, which is what lets another
    // project's analyzer see that a method it calls is marked.
    public const string Source =
        """
        // <auto-generated/>
        namespace Motiv.Explain
        {
            /// <summary>
            /// Marks a boolean method whose calls an explain build (<c>MotivExplain=true</c>) replaces with a
            /// decomposed Motiv specification that logs why it was true or false. Other builds ignore it.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
            [global::System.Diagnostics.Conditional("MOTIV_EXPLAIN")]
            [global::Microsoft.CodeAnalysis.Embedded]
            internal sealed class ExplainAttribute : global::System.Attribute
            {
            }
        }
        """;

    public static bool IsOn(ISymbol symbol) =>
        symbol.GetAttributes().Any(attribute => attribute.AttributeClass?.ToDisplayString() == MetadataName);
}
