using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Motiv.Explain;

/// <summary>An eligible <c>[Explain]</c> method and the calls to it that the build will replace.</summary>
internal sealed record ExplainTarget(
    IMethodSymbol Method,
    MethodDeclarationSyntax Declaration,
    ExpressionSyntax Body,
    SemanticModel Model,
    int Ordinal,
    IReadOnlyList<string> InterceptsLocationAttributes);

/// <summary>
///     The values a clause can read (<c>this</c> for an instance method, then the parameters), packed into the
///     one model a Motiv spec evaluates. Its type, how the interceptor packs it and how a clause unpacks it
///     must always agree, so all three are rendered here.
/// </summary>
internal sealed class ModelShape
{
    // Prefixed so no parameter or member of the user's type can share or hide the names
    public const string Parameter = "__motivModel";

    private readonly IReadOnlyList<(string Name, ITypeSymbol Type)> _values;

    public ModelShape(IMethodSymbol method, SymbolDisplayFormat typeFormat)
    {
        _values =
        [
            .. method.IsStatic ? [] : new[] { (MemberAccessRewriter.Receiver, (ITypeSymbol)method.ContainingType) },
            .. method.Parameters.Select(parameter => (Escape(parameter.Name), parameter.Type))
        ];
        Type = _values.Count switch
        {
            0 => "object?",
            1 => _values[0].Type.ToDisplayString(typeFormat),
            _ => $"({string.Join(", ", _values.Select(value => value.Type.ToDisplayString(typeFormat)))})"
        };
        InterceptorParameters = string.Join(", ", _values.Select((value, index) =>
            (index == 0 && !method.IsStatic ? "this " : "") + $"{value.Type.ToDisplayString(typeFormat)} {value.Name}"));
    }

    /// <summary>The model's type, for example <c>(global::Shop.Pricing, global::Shop.Order)</c>.</summary>
    public string Type { get; }

    /// <summary>The interceptor's parameter list, which matches the intercepted method's signature.</summary>
    public string InterceptorParameters { get; }

    /// <summary>The expression that packs the interceptor's parameters into a model.</summary>
    public string Pack => _values.Count switch
    {
        0 => "null",
        1 => _values[0].Name,
        _ => $"({Names})"
    };

    /// <summary>The statements that unpack a model into locals named as in the method, so a clause reads unchanged.</summary>
    // One declaration per element rather than a deconstruction, where a parameter named _ would be a discard
    public string Unpack => _values.Count switch
    {
        0 => "",
        1 => $"var {_values[0].Name} = {Parameter}; ",
        _ => string.Concat(_values.Select((value, index) => $"var {value.Name} = {Parameter}.Item{index + 1}; "))
    };

    private string Names => string.Join(", ", _values.Select(value => value.Name));

    private static string Escape(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;
}

/// <summary>
///     Writes one file per explained method. The decomposed spec goes in a nested class of the method's own
///     (partial) type, so its clauses can read everything the method can. The interceptor that evaluates it
///     goes in <c>Motiv.Explain.Generated</c>, the one namespace <c>build/Motiv.Explain.targets</c> allows.
/// </summary>
internal static class ExplainSourceWriter
{
    public const string InterceptorNamespace = "Motiv.Explain.Generated";

    private static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    // Keywords come out escaped (@event), and the declarations they name are written one level at a time
    private static readonly SymbolDisplayFormat NamespaceFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted);

    private static readonly SymbolDisplayFormat TypeNameFormat = new(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameOnly,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public const string LogSource =
        """
        // <auto-generated/>
        #nullable enable
        namespace Motiv.Explain
        {
            /// <summary>Receives every decision an explain build logs. Exists only when MotivExplain=true.</summary>
            [global::Microsoft.CodeAnalysis.Embedded]
            internal static class MotivExplainLog
            {
                /// <summary>Where each explained decision goes. Defaults to <see cref="global::System.Diagnostics.Trace"/>; set it to null to stop logging.</summary>
                public static global::System.Action<ExplainedDecision>? Sink { get; set; } =
                    decision => global::System.Diagnostics.Trace.WriteLine(decision.ToString());

                internal static bool Write(string member, global::Motiv.BooleanResultBase<string> result)
                {
                    Sink?.Invoke(new ExplainedDecision(member, result));
                    return result.Satisfied;
                }
            }

            /// <summary>One call to an [Explain] method: which method, and the Motiv result that explains its answer.</summary>
            [global::Microsoft.CodeAnalysis.Embedded]
            internal sealed class ExplainedDecision
            {
                internal ExplainedDecision(string member, global::Motiv.BooleanResultBase<string> result)
                {
                    Member = member;
                    Result = result;
                }

                /// <summary>The method that was called, for example <c>Shop.Rules.IsEligible(Shop.Order)</c>.</summary>
                public string Member { get; }

                /// <summary>The evaluation, with its <c>Justification</c>, <c>Reason</c> and <c>Assertions</c>.</summary>
                public global::Motiv.BooleanResultBase<string> Result { get; }

                /// <summary>The method's answer.</summary>
                public bool Satisfied => Result.Satisfied;

                /// <inheritdoc />
                public override string ToString() =>
                    "[motiv-explain] " + Member + " => " + Result.Satisfied + "\n" + Result.Justification;
            }
        }
        """;

    public static string HintName(ExplainTarget target) => UniqueName(target) + ".g.cs";

    public static string Write(ExplainTarget target)
    {
        var model = new ModelShape(target.Method, TypeFormat);
        var holder = $"__MotivExplain_{target.Method.Name}_{target.Ordinal}";
        var source = new StringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            // The clauses are the user's code, split apart: a null check and the dereference it guarded can
            // land in different delegates, so flow analysis would warn about code that is in fact safe.
            .AppendLine("#pragma warning disable");

        foreach (var directive in Usings(target.Declaration, namespaceScoped: false))
            source.AppendLine(directive);

        WriteHolder(source, target, model, holder);
        WriteInterceptor(source, target, model, holder);
        WriteInterceptsLocationAttribute(source);
        return source.ToString();
    }

    private static void WriteHolder(StringBuilder source, ExplainTarget target, ModelShape model, string holder)
    {
        var method = target.Method;
        var types = Enclosing(method.ContainingType).ToList();
        var ns = method.ContainingType.ContainingNamespace;

        if (!ns.IsGlobalNamespace)
        {
            source.AppendLine($"namespace {ns.ToDisplayString(NamespaceFormat)}").AppendLine("{");
            // A using inside a namespace resolves relative to it, so it has to stay inside one
            foreach (var directive in Usings(target.Declaration, namespaceScoped: true))
                source.AppendLine(directive);
        }
        foreach (var type in types)
            source.AppendLine($"partial {(type.IsRecord ? "record" : "class")} {type.ToDisplayString(TypeNameFormat)}").AppendLine("{");

        var decomposer = new ClauseDecomposer(target.Model, clause => Clause(clause, target, model));
        source
            .AppendLine($"    internal static {(IsUnsafe(target.Declaration) ? "unsafe " : "")}class {holder}")
            .AppendLine("    {")
            .AppendLine($"        internal static readonly global::Motiv.SpecBase<{model.Type}, string> {SpecField} =")
            .AppendLine($"            {decomposer.Render(target.Body)};")
            .AppendLine("    }");

        foreach (var _ in types)
            source.AppendLine("}");
        if (!ns.IsGlobalNamespace)
            source.AppendLine("}");
    }

    // Prefixed: a clause compiles inside the holder, where this name would hide a user member of the same name
    private const string SpecField = "__MotivExplainSpec";

    private static string Clause(IReadOnlyList<ExpressionSyntax> clause, ExplainTarget target, ModelShape model)
    {
        var text = ClauseText.Of(clause);
        var code = MemberAccessRewriter.Rewrite(clause, text, target.Model);
        var statement = SymbolDisplay.FormatLiteral(Normalize(text), quote: true);

        return $"global::Motiv.Spec.Build(({model.Type} {ModelShape.Parameter}) => {{ {model.Unpack}return {code}; }}).Create({statement})";
    }

    private static void WriteInterceptor(StringBuilder source, ExplainTarget target, ModelShape model, string holder)
    {
        var method = target.Method;
        var member = SymbolDisplay.FormatLiteral(method.ToDisplayString(), quote: true);

        source
            .AppendLine($"namespace {InterceptorNamespace}")
            .AppendLine("{")
            .AppendLine($"    internal static class {UniqueName(target)}")
            .AppendLine("    {");
        foreach (var attribute in target.InterceptsLocationAttributes)
            source.AppendLine($"        {attribute}");
        // No locals and only globally qualified names, so no parameter name can clash or shadow
        source
            .AppendLine($"        internal static bool Intercept({model.InterceptorParameters})")
            .AppendLine("        {")
            .AppendLine($"            return global::Motiv.Explain.MotivExplainLog.Write({member}, {method.ContainingType.ToDisplayString(TypeFormat)}.{holder}.{SpecField}.Evaluate({model.Pack}));")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine("}");
    }

    // A file-local copy, as the interceptors design recommends, so it can't clash with another generator's
    private static void WriteInterceptsLocationAttribute(StringBuilder source) =>
        source.AppendLine(
            """
            namespace System.Runtime.CompilerServices
            {
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute : global::System.Attribute
                {
                    public InterceptsLocationAttribute(int version, string data) { }
                }
            }
            """);

    // The clauses keep their original text, so they need the names the original file imported
    private static IEnumerable<string> Usings(SyntaxNode declaration, bool namespaceScoped) =>
        declaration.Ancestors()
            .Reverse()
            .SelectMany(node => node switch
            {
                CompilationUnitSyntax unit when !namespaceScoped => unit.Usings,
                BaseNamespaceDeclarationSyntax ns when namespaceScoped => ns.Usings,
                _ => default(SyntaxList<UsingDirectiveSyntax>)
            })
            .Where(directive => directive.GlobalKeyword.IsKind(SyntaxKind.None))
            .Select(directive => directive.ToString())
            .Distinct();

    // A pointer in a clause needs the unsafe context the method had, from its own modifier or its type's
    private static bool IsUnsafe(MethodDeclarationSyntax declaration) =>
        declaration.Modifiers.Any(SyntaxKind.UnsafeKeyword) ||
        declaration.Ancestors().OfType<TypeDeclarationSyntax>().Any(type => type.Modifiers.Any(SyntaxKind.UnsafeKeyword));

    private static IEnumerable<INamedTypeSymbol> Enclosing(INamedTypeSymbol type) =>
        type.ContainingType is null ? [type] : [.. Enclosing(type.ContainingType), type];

    // Sanitising can map two methods to one name (A_B.C and A.B_C), so a hash of the real name keeps them apart
    private static string UniqueName(ExplainTarget target)
    {
        var name = $"{target.Method.ContainingType.ToDisplayString()}.{target.Method.Name}";
        var readable = new string(name.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
        return $"__MotivExplain_{readable}_{target.Ordinal}_{StableHash(name):x8}";
    }

    // FNV-1a: string.GetHashCode is randomised per process, which would rename files from build to build
    private static uint StableHash(string text)
    {
        var hash = 2166136261;
        foreach (var c in text)
            hash = (hash ^ c) * 16777619;
        return hash;
    }

    private static string Normalize(string text) =>
        string.Join(" ", text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
}
