# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        framework: [netstandard2.0, net8.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Karlssberg.Motiv/Karlssberg.Motiv.csproj --configuration Release --no-restore -f ${{ matrix.framework }} -o ./bin/Release/${{ matrix.framework }}
    - name: Test
      run: dotnet test --verbosity normal
    - name: List Build Artifacts
      run: ls -R ./bin/Release
    - name: Pack
      run: dotnet pack Karlssberg.Motiv/Karlssberg.Motiv.csproj --configuration Release --output nupkgs -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    - name: Publish to NuGet
      run: dotnet nuget push "nupkgs/**/*.nupkg" --api-key ${{secrets.MOTIV_API_KEY}} --source https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/main'