# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ['netstandard2.0', 'net8.0']
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Build for ${{ matrix.framework }}
      run: dotnet build Karlssberg.Motiv/Karlssberg.Motiv.csproj --configuration Release --framework ${{ matrix.framework }} --no-restore -o ./Karlssberg.Motiv/bin/Release/${{ matrix.framework }}/
    - name: List Build Artifacts
      run: find "$(pwd)/Karlssberg.Motiv/bin/Release" -type f
    - name: Pack for ${{ matrix.framework }}
      run: dotnet pack Karlssberg.Motiv/Karlssberg.Motiv.csproj --configuration Release --no-build -p:TargetFrameworks=${{ matrix.framework }} --output nupkgs/${{ matrix.framework }}
    - name: Publish to NuGet
      run: dotnet nuget push "nupkgs/**/*.nupkg" --api-key ${{secrets.MOTIV_API_KEY}} --source https://api.nuget.org/v3/index.json
      if: github.ref == 'refs/heads/main'